const navBarTitles = [
  "Home",
  "About",
  "Skills",
  "Projects",
  "Contact",
  // "Experience",
  // "Contact",
] as const;

const projectsImagesSkills = [
  // docker and kubernetes in learning journey
  { filename: "javascript.svg", name: "javascript" },
  { filename: "sql.png",name : "sql"},
  // { filename: "sql1.png",name : "sql"},
  
  { filename: "typescript.svg", name: "typescript" },
  { filename: "nextjs.svg", name: "next js" },
  { filename: "react.svg", name: "react" },
  // { filename: "astrojs.svg", name: "astro js" }, if it commented i will learn it later because you must limit your skills
  // { filename: "tauri.svg", name: "tauri" },
  // { filename: "electronjs.svg", name: "electron js" },
  { filename: "tailwindcss.svg", name: "tailwind css" },
  { filename: "reactrouter.svg", name: "react router" },
  { filename: "reduxtoolkit.svg", name: "redux toolkit" },
  // { filename: "reactquery.svg", name: "react query" },
  // { filename: "swr.svg", name: "swr" },
  { filename: "prisma.svg", name: "prisma" },
  { filename: "zodlogo.svg", name: "zod" },
  // { filename: "langchain.png", name: "langchain" },
  { filename: "nextauth.webp", name: "next auth" },
  // { filename: "auth0.svg", name: "auth0" },
  { filename: "nodejs.svg", name: "node js" },
  { filename: "deno.svg", name: "deno" },
  { filename: "jwt.svg", name: "jwt" },
  { filename: "expressjs.svg", name: "express js" },
  // { filename: "nestjs.svg", name: "nest js" },
  // { filename: "sanity.svg", name: "sanity" },
  { filename: "supabase.svg", name: "supabase" },
  { filename: "firebase.svg", name: "firebase" },
  { filename: "mongodb.svg", name: "mongodb" },
  { filename: "icons8-git.svg", name: "git" },
  { filename: "stripe.svg", name: "stripe" },
  

  { filename: "postgressql.svg", name: "postgressql" },
  // { filename: "mysql.svg", name: "mysql" },
  // { filename: "sqlite.svg", name: "sqlite" },
] as const;
// const projectsImagesSkills = [
//   { filename: "typescript.svg", name: "typescript" },
//   { filename: "nextjs.svg", name: "next js" },
//   { filename: "react.svg", name: "react" },
//   { filename: "astrojs.svg", name: "astro js" },
//   { filename: "tauri.svg", name: "tauri" },
//   { filename: "electronjs.svg", name: "electron js" },
//   { filename: "tailwindcss.svg", name: "tailwind css" },
//   { filename: "reactrouter.svg", name: "react router" },
//   { filename: "reduxtoolkit.svg", name: "redux toolkit" },
//   { filename: "reactquery.svg", name: "react query" },
//   { filename: "swr.svg", name: "swr" },
//   { filename: "postgressql.svg", name: "postgressql" },
//   { filename: "prisma.svg", name: "prisma" },
//   { filename: "zodlogo.svg", name: "zod" },
//   { filename: "langchain.png", name: "langchain" },
//   { filename: "nextauth.webp", name: "next auth" },
//   { filename: "auth0.svg", name: "auth0" },
//   { filename: "nodejs.svg", name: "node js" },
//   { filename: "deno.svg", name: "deno" },
//   { filename: "jwt.svg", name: "jwt" },
//   { filename: "expressjs.svg", name: "express js" },
//   { filename: "nestjs.svg", name: "nest js" },
//   { filename: "sanity.svg", name: "sanity" },
//   { filename: "supabase.svg", name: "supabase" },
//   { filename: "firebase.svg", name: "firebase" },
//   { filename: "mongodb.svg", name: "mongodb" },
//   { filename: "mysql.svg", name: "mysql" },
//   { filename: "sqlite.svg", name: "sqlite" },
// ] as const;

export { navBarTitles, projectsImagesSkills };
