version: "3.8"
services:
  nextjs-app:
    image: portfolio
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "4000:4000"
    # environment: since we are using .env file, we don't need to specify environment variables here
    #   - NODE_ENV=production
    restart: always
    env_file:
      - .env
