name: Deploy Next.js site to VPS

on:
  push:
    branches: [main]
  workflow_dispatch: # Enable manual triggering

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [18.x] # Use Node.js 18.x
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}      
      - name: Deploy to VPS
        run: |
          cd /home/mohamed/projects/Mohamed-gp.github.io
          git pull origin main
          npm install
          npm run build
          pm2 restart portfolio
