name: Deploy Next.js site to VPS with Docker

on:
  push:
    branches: [main] # if i enable the pull request the anyone can use the self hosted and do anything including malcious code
  workflow_dispatch: # Enable manual triggering

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [18.x] # Use Node.js 18.x
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Push Docker image to VPS and deploy
        run: |
          cd ${{ secrets.REPO_LOCATION_IN_VPS }} || exit 1
          git pull origin main || exit 1
          docker-compose down || exit 1
          docker-compose up --build -d || exit 1

# name: Deploy Next.js site to VPS without Docker

# on:
#   push:
#     branches: [main]
#   workflow_dispatch: # Enable manual triggering

# jobs:
#   build:
#     runs-on: self-hosted
#     strategy:
#       matrix:
#         node-version: [18.x] # Use Node.js 18.x
#     steps:
#       - uses: actions/checkout@v2
#       - name: Use Node.js ${{ matrix.node-version }}
#         uses: actions/setup-node@v1
#         with:
#           node-version: ${{ matrix.node-version }}
#       - name: Deploy to VPS
#         run: |
#           cd /home/mohamed/projects/Mohamed-gp.github.io
#           git pull origin main
#           npm install
#           npm run build
#           pm2 restart portfolio
