name: Deploy Next.js site to VPS

on:
  push:
    branches: [main]
  workflow_dispatch: # Enable manual triggering

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [18.x] # Use Node.js 18.x
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run build --if-present
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa
          ssh-keyscan -p 22 -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts
      - name: Deploy to VPS
        run: |
          cd /home/mohamed/projects/Mohamed-gp.github.io
          npm install
          npm run build
          pm2 restart portfolio
